# Generated by Django 5.0.1 on 2024-01-24 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id_autor', models.AutoField(primary_key=True, serialize=False)),
                ('imie_autor', models.CharField(max_length=255)),
                ('nazwisko_autor', models.CharField(max_length=255)),
                ('kraj_pochodzenia', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'autorzy',
            },
        ),
        migrations.CreateModel(
            name='Karta',
            fields=[
                ('id_karty_bibl', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=255)),
                ('nazwisko', models.CharField(max_length=255)),
                ('pesel', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'dane_karty_i_posiadacza',
            },
        ),
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id_kategorii', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa_kategorii', models.CharField(max_length=255)),
                ('czy_mozna_wypozyczyc', models.BooleanField()),
            ],
            options={
                'db_table': 'kategorie',
            },
        ),
        migrations.CreateModel(
            name='Pracownicy',
            fields=[
                ('id_pracownika', models.AutoField(primary_key=True, serialize=False)),
                ('nazwisko', models.CharField(max_length=255)),
                ('imie', models.CharField(max_length=255)),
                ('data_zatrudnienia', models.DateField()),
                ('stanowisko', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'pracownicy',
            },
        ),
        migrations.CreateModel(
            name='Wydawnictwa',
            fields=[
                ('id_wydawnictwa', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=255)),
                ('rok_zalozenia', models.IntegerField()),
                ('kraj', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'wydawnictwa',
            },
        ),
        migrations.CreateModel(
            name='DaneAdresowe',
            fields=[
                ('id_karty_bibl', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='formularz.karta')),
                ('ulica', models.CharField(max_length=255)),
                ('numer_budynku', models.IntegerField()),
                ('numer_lokalu', models.IntegerField()),
                ('kod_pocztowy', models.CharField(max_length=9)),
                ('miejscowosc', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dane_adresowe',
            },
        ),
        migrations.CreateModel(
            name='Ksiazka',
            fields=[
                ('id_ksiazki', models.AutoField(primary_key=True, serialize=False)),
                ('tytul', models.CharField(max_length=255)),
                ('nr_wydania', models.IntegerField()),
                ('dostepnych', models.IntegerField()),
                ('wypozyczonych', models.IntegerField()),
                ('id_autor', models.ForeignKey(default='brak autora', on_delete=django.db.models.deletion.SET_DEFAULT, to='formularz.autor')),
                ('id_kategorii', models.ForeignKey(default='brak kategorii', on_delete=django.db.models.deletion.SET_DEFAULT, to='formularz.kategorie')),
                ('id_wydawnictwa', models.ForeignKey(default='brak wydawnictwa', on_delete=django.db.models.deletion.SET_DEFAULT, to='formularz.wydawnictwa')),
            ],
            options={
                'db_table': 'dane_ksiazek',
            },
        ),
        migrations.CreateModel(
            name='Rezerwacje',
            fields=[
                ('id_rezerwacji', models.AutoField(primary_key=True, serialize=False)),
                ('data_rezerwacji', models.DateField()),
                ('czy_wypozyczono', models.BooleanField()),
                ('data_wypozyczenia_lub_anulacji', models.DateField()),
                ('id_karty_bibl', models.ForeignKey(default='brak numeru karty', on_delete=django.db.models.deletion.SET_DEFAULT, to='formularz.karta')),
                ('id_ksiazki', models.ForeignKey(default='brak ksiazki', on_delete=django.db.models.deletion.SET_DEFAULT, to='formularz.ksiazka')),
            ],
            options={
                'db_table': 'rezerwacje',
            },
        ),
        migrations.CreateModel(
            name='StatystykiWypozyczen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc_wypozyczonych', models.IntegerField()),
                ('ilosc_oddanych', models.IntegerField()),
                ('ilosc_przetrzymanych', models.IntegerField()),
                ('zaleglosc_za_przetrzymanie', models.IntegerField()),
                ('id_karty_bibl', models.ForeignKey(default='brak numeru karty', on_delete=django.db.models.deletion.SET_DEFAULT, to='formularz.karta')),
            ],
            options={
                'db_table': 'statystyki_wypozyczen',
            },
        ),
        migrations.CreateModel(
            name='Wypozyczenia',
            fields=[
                ('id_wypozyczenia', models.AutoField(primary_key=True, serialize=False)),
                ('data_wypozyczenia', models.DateField()),
                ('data_zwrotu', models.DateField()),
                ('czy_zwrocona', models.BooleanField()),
                ('czy_po_terminie', models.BooleanField()),
                ('id_karty_bibl', models.ForeignKey(default='brak numeru karty', on_delete=django.db.models.deletion.SET_DEFAULT, to='formularz.karta')),
                ('id_ksiazki', models.ForeignKey(default='brak ksiazki', on_delete=django.db.models.deletion.SET_DEFAULT, to='formularz.ksiazka')),
                ('id_pracownika', models.ForeignKey(default='brak pracownika', on_delete=django.db.models.deletion.SET_DEFAULT, to='formularz.pracownicy')),
            ],
            options={
                'db_table': 'dane_wypozyczen',
            },
        ),
    ]
